### ISSUE TITLE
Handle strings that have interpolation

### ISSUE THREAD

**Issue by jamieshark** [jamieshark/i18n-html_extractor#3]
There are strings where we might be rendering a string as a variable. Since `gettext` has way of handling interpolation as string arguments, we need to wrap the string and replace the arguments accordingly.

```ruby
# Before extraction
<div>
   You submitted <%= count %> times!
</div>

# After extraction
<div>
   <%= "You submitted %{count} times!", count: count %>
</div>
```

**Comment by MrChrisW** [comment]
Updated example:

```erb
# After extraction
<%= _("You submitted %{count} times!") % { count: count } %>
```
https://github.com/grosser/fast_gettext/blob/master/Readme.md#4-start-translating

**Comment by jamieshark** [comment]
https://github.com/github/i18n-tools/issues
